<script>
  import { site } from '$lib/data/site.js';
</script>

<svelte:head>
  <title>تماس، آدرس و رزرو مشاوره | 4B Clinic</title>
  <meta name="description" content="شماره تماس، آدرس 4B Clinic تهران و راه‌های رسمی ارتباط برای هماهنگی ارزیابی اولیه و مراجعه." />
  <link rel="canonical" href="https://4b-clinic.com/contact" />
</svelte:head>

<section class="contact-v2-hero"><div><div class="eyebrow light">CONTACT • BOOKING • TEHRAN</div><h1>ارتباط با<br/><span>4B Clinic</span></h1><p>برای درخواست ارزیابی اولیه، هماهنگی مراجعه و ارسال مدارک از مسیرهای رسمی کلینیک استفاده کنید.</p></div><div class="contact-hero-card"><small>تهران • قیطریه</small><p>{site.contact.address}</p>{#each site.contact.phones as phone}<a href={phone.href} dir="ltr">{phone.display}</a>{/each}</div></section>

<section class="direct-v2"><div class="section-head-v2"><div><div class="eyebrow">DIRECT CONTACT</div><h2>تماس مستقیم و مراجعه حضوری</h2></div><p>برای هماهنگی نوبت یا پرسش‌های مربوط به مراجعه، از شماره‌های رسمی زیر استفاده کنید.</p></div><div class="contact-cards-v2">{#each site.contact.phones as phone}<a href={phone.href}><small>{phone.label}</small><strong dir="ltr">{phone.display}</strong><span>تماس مستقیم ←</span></a>{/each}<div class="address-v2"><small>آدرس کلینیک</small><strong>{site.contact.address}</strong><span>تهران • قیطریه</span></div></div></section>

<section class="prepare-v2"><div><div class="eyebrow light">BEFORE YOU CONTACT</div><h2>برای ارزیابی اولیه چه اطلاعاتی آماده باشد؟</h2><p>شرح حال کوتاه و مدارک مرتبط کمک می‌کنند سریع‌تر بفهمیم چه نوع ارزیابی برای شما مناسب است.</p></div><div class="prep-grid"><span><b>01</b> مشکل اصلی و مدت شروع علائم</span><span><b>02</b> درمان‌های قبلی و نتیجه آنها</span><span><b>03</b> MRI، رادیوگرافی یا گزارش‌های مرتبط</span><span><b>04</b> داروهای مهم و بیماری‌های زمینه‌ای</span></div></section>

<section class="social-v2"><div><div class="eyebrow">OFFICIAL CHANNELS</div><h2>شبکه‌های رسمی 4B</h2><p>لینک هر شبکه فقط بعد از تأیید حساب رسمی فعال می‌شود تا بیمار به صفحه اشتباه هدایت نشود و مسیر ارتباطی قابل اعتماد باقی بماند.</p></div><div class="social-grid-v2">{#each site.socials as social}{#if social.href}<a href={social.href} target="_blank" rel="noreferrer"><span>{social.label.slice(0,1)}</span><div><strong>{social.label}</strong>{#if social.handle}<small>{social.handle}</small>{/if}</div><b>ورود ↗</b></a>{:else}<div class="pending"><span>{social.label.slice(0,1)}</span><div><strong>{social.label}</strong><small>در انتظار تأیید لینک رسمی</small></div><b>به‌زودی</b></div>{/if}{/each}</div></section>

<section class="booking-v2"><div><div class="eyebrow light">BOOKING FLOW</div><h2>مسیر هماهنگی مراجعه</h2></div><div class="booking-grid"><span><b>1</b> تماس یا ارسال درخواست اولیه</span><span><b>2</b> بررسی موضوع مراجعه و مدارک لازم</span><span><b>3</b> تعیین زمان مناسب برای ارزیابی حضوری</span></div></section>

<style>
  .eyebrow{font-size:10px;letter-spacing:.16em;color:#9a7331;font-weight:900}.eyebrow.light{color:#ddc287}.contact-v2-hero{padding:clamp(90px,11vw,150px) clamp(20px,7vw,110px);display:grid;grid-template-columns:1fr .8fr;gap:70px;align-items:center;background:linear-gradient(135deg,#07172b,#12385f);color:#fff}.contact-v2-hero h1{font-size:clamp(48px,7vw,96px);line-height:1.08;margin:12px 0 20px}.contact-v2-hero h1 span{color:#ddc287}.contact-v2-hero>div:first-child>p{font-size:18px;color:#d0d9e1;max-width:700px}.contact-hero-card{padding:28px;border:1px solid rgba(255,255,255,.16);border-radius:22px;background:rgba(255,255,255,.06);backdrop-filter:blur(10px);display:grid;gap:8px}.contact-hero-card small{color:#d9c08a}.contact-hero-card p{color:#c5ced7}.contact-hero-card a{padding:10px 12px;border:1px solid rgba(255,255,255,.18);border-radius:12px;color:#fff;text-decoration:none;text-align:center;background:rgba(255,255,255,.04)}
  .direct-v2,.social-v2{padding:clamp(66px,8vw,112px) clamp(20px,7vw,110px);background:#fff}.section-head-v2{display:grid;grid-template-columns:1fr minmax(280px,.72fr);gap:60px;align-items:end;margin-bottom:34px}.section-head-v2 h2,.prepare-v2 h2,.social-v2 h2,.booking-v2 h2{font-size:clamp(30px,4.4vw,56px);line-height:1.42;margin:10px 0}.section-head-v2>p,.social-v2>div:first-child>p{color:#65717b;margin:0}.contact-cards-v2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.contact-cards-v2>a,.address-v2{padding:24px;border:1px solid #e0e4e1;border-radius:18px;background:#fafaf8;display:grid;gap:5px;text-decoration:none;color:#1d2c39}.contact-cards-v2 small,.address-v2 small{color:#9a7331}.contact-cards-v2 strong,.address-v2 strong{font-size:clamp(21px,3vw,30px);line-height:1.6}.contact-cards-v2 span,.address-v2 span{color:#6b7680;font-size:12px}.address-v2{grid-column:1/-1}.address-v2 strong{font-size:18px}
  .prepare-v2{padding:clamp(68px,9vw,122px) clamp(20px,7vw,110px);background:#07172b;color:#fff;display:grid;grid-template-columns:.78fr 1.22fr;gap:70px}.prepare-v2>div:first-child>p{color:#bbc6cf}.prep-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.prep-grid span{padding:18px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.045);border-radius:16px;color:#d5dde4}.prep-grid b{display:inline-grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#b58d48;margin-left:8px;color:#fff;font-size:10px}
  .social-v2{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px}.social-grid-v2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.social-grid-v2>a,.social-grid-v2>.pending{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:14px;padding:18px;border:1px solid #e0e4e1;border-radius:16px;background:#fafaf8;text-decoration:none;color:#24313d}.social-grid-v2>a>span,.social-grid-v2>.pending>span{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:#07172b;color:#d9bd82;font-weight:900}.social-grid-v2 div>div{display:grid}.social-grid-v2 small{color:#7b8790}.social-grid-v2 b{font-size:11px;color:#9a7331}.pending{opacity:.7}.booking-v2{padding:clamp(66px,8vw,112px) clamp(20px,7vw,110px);background:#0a1d32;color:#fff}.booking-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:30px}.booking-grid span{padding:18px;border:1px solid #263d55;border-radius:15px;color:#d3dce4}.booking-grid b{display:inline-grid;place-items:center;width:27px;height:27px;border-radius:50%;background:#b58d48;margin-left:8px}
  @media(max-width:900px){.contact-v2-hero,.section-head-v2,.prepare-v2,.social-v2{grid-template-columns:1fr;gap:28px}.booking-grid{grid-template-columns:1fr}}
  @media(max-width:620px){.contact-v2-hero h1{font-size:46px}.contact-cards-v2,.prep-grid,.social-grid-v2{grid-template-columns:1fr}.address-v2{grid-column:auto}}
</style>
