<script>
  const articles = [
    { image:'/images/services/knee.webp', tag:'زانو و آرتروز', title:'درد زانو؛ از علت درد تا انتخاب درمان', text:'درد زانو می‌تواند از آرتروز، منیسک، رباط‌ها، محور اندام یا التهاب ناشی شود. قبل از انتخاب هر درمانی باید مشخص شود مشکل اصلی کجاست و شدت آن چقدر است.', href:'https://zetamed.org/knee-pain/', label:'مطالعه کامل درباره درد زانو در Zetamed' },
    { image:'/images/services/shoulder.webp', tag:'ارتوبیولوژیک', title:'ارتوبیولوژیک دقیقاً چیست؟', text:'ارتوبیولوژیک از دانش سلولی و مولکولی برای مدیریت برخی آسیب‌های سیستم اسکلتی‌عضلانی استفاده می‌کند. روش مناسب به بافت درگیر، شدت بیماری و هدف درمان بستگی دارد.', href:'https://zetamed.org/services/orthobiological/', label:'مطالعه علمی ارتوبیولوژیک در Zetamed' },
    { image:'/images/services/hair.webp', tag:'PL • PRGF', title:'فاکتورهای رشد پلاکتی چه نقشی در ترمیم دارند؟', text:'پلاکت‌ها فقط در انعقاد خون نقش ندارند و مجموعه‌ای از پیام‌رسان‌های زیستی و فاکتورهای رشد را آزاد می‌کنند. فرآوری این منابع، پایه برخی روش‌های اتولوگ مانند PRGF و PL است.', href:'https://zetamed.org/%D9%81%D8%A7%DA%A9%D8%AA%D9%88%D8%B1%D9%87%D8%A7%DB%8C-%D8%B1%D8%B4%D8%AF%DB%8C-%DA%A9%D9%87-%D8%A7%D8%B2-%D9%BE%D9%84%D8%A7%DA%A9%D8%AA%D9%87%D8%A7-%D8%A8%D9%87-%D8%AF%D8%B3%D8%AA-%D9%85/', label:'اطلاعات علمی فاکتورهای رشد در Zetamed' },
    { image:null, tag:'زخم مزمن', title:'چرا بعضی زخم‌ها دیر خوب می‌شوند؟', text:'در زخم مزمن فقط سطح زخم مهم نیست. خون‌رسانی، فشار، عفونت، کنترل دیابت، تغذیه و کیفیت بستر زخم همزمان روی روند ترمیم اثر می‌گذارند.', href:'https://zetamed.org/services/wound-clinic/', label:'مطالعه بیشتر درباره زخم در Zetamed' },
    { image:'/images/services/skin.webp', tag:'پزشکی بازساختی', title:'پزشکی بازساختی؛ از وعده‌های بزرگ تا کاربرد واقعی', text:'پزشکی بازساختی به معنی رشد دوباره همه بافت‌ها نیست. این حوزه مجموعه‌ای از روش‌های سلولی، مولکولی و مهندسی بافت است که باید بر اساس شواهد و محدودیت‌های هر کاربرد بررسی شود.', href:'https://zetamed.org/%D9%BE%D8%B2%D8%B4%DA%A9%DB%8C-%D8%A8%D8%A7%D8%B2%D8%B3%D8%A7%D8%AE%D8%AA%DB%8C-%D9%85%D9%82%D8%AF%D9%85%D9%87/', label:'مقدمه علمی پزشکی بازساختی در Zetamed' },
    { image:'/images/services/sexual-health.webp', tag:'کتابخانه علمی', title:'برای مطالعه عمیق‌تر کجا برویم؟', text:'مقالات 4B برای تصمیم‌گیری بیمار نوشته می‌شوند. برای جزئیات مکانیزم‌ها، فاکتورهای رشد، سلول‌ها و محتوای علمی گسترده‌تر، کتابخانه Zetamed مرجع مکمل ماست.', href:'https://zetamed.org/blog/', label:'ورود به کتابخانه Zetamed' }
  ];
</script>

<svelte:head>
  <title>مقالات و راهنمای بیماران | 4B Clinic</title>
  <meta name="description" content="راهنمای بیمارمحور 4B Clinic درباره درد زانو، ارتوبیولوژیک، درمان‌های اتولوگ، فاکتورهای رشد و زخم مزمن؛ همراه با لینک مطالعه علمی بیشتر در Zetamed." />
  <link rel="canonical" href="https://4b-clinic.com/articles" />
</svelte:head>

<section class="articles-v2-hero"><div class="eyebrow light">4B KNOWLEDGE</div><h1>مقاله برای تصمیم بهتر،<br/><span>نه برای پیچیده‌تر کردن درمان</span></h1><p>مطالب 4B کوتاه، قابل‌فهم و بیمارمحور می‌مانند. برای جزئیات علمی، مکانیزم‌ها و مباحث سلولی مولکولی، هر موضوع به صفحه مرتبط در Zetamed وصل می‌شود.</p></section>

<section class="article-intro-v2"><div><div class="eyebrow">PATIENT FIRST</div><h2>دو لایه محتوا، برای دو نیاز متفاوت</h2></div><p><strong>4B Clinic</strong> پاسخ می‌دهد «این موضوع برای بیمار چه معنایی دارد؟» و <strong>Zetamed</strong> وارد جزئیات علمی، مکانیزم‌ها و مبانی پزشکی سلولی مولکولی می‌شود.</p></section>

<section class="article-grid-v2">{#each articles as article}<article class:graphic={!article.image} class="article-v2-card">{#if article.image}<div class="article-image"><img src={article.image} alt="" loading="lazy"/><span></span></div>{:else}<div class="article-image wound-graphic"><i></i><i></i><i></i><b>WOUND</b></div>{/if}<div class="article-copy-v2"><span class="tag">{article.tag}</span><h2>{article.title}</h2><p>{article.text}</p><a href={article.href} target="_blank" rel="noopener noreferrer">{article.label} ↗</a></div></article>{/each}</section>

<section class="editorial-v2"><div><div class="eyebrow light">EDITORIAL PRINCIPLE</div><h2>محتوای سایت جایگزین ویزیت پزشکی نیست.</h2><p>مطالب این بخش برای آشنایی و تصمیم‌گیری بهتر طراحی شده‌اند. تشخیص و انتخاب درمان به شرح حال، معاینه، تصویربرداری و شرایط هر بیمار وابسته است.</p></div><a href="/contact">درخواست ارزیابی</a></section>

<style>
  .eyebrow{font-size:10px;letter-spacing:.16em;color:#9a7331;font-weight:900}.eyebrow.light{color:#ddc287}.articles-v2-hero{padding:clamp(100px,13vw,180px) clamp(20px,7vw,110px);background:linear-gradient(135deg,#07172b,#12385f);color:#fff}.articles-v2-hero h1{font-size:clamp(46px,6.6vw,90px);line-height:1.12;margin:12px 0 20px}.articles-v2-hero h1 span{color:#ddc287}.articles-v2-hero p{max-width:900px;color:#d0d9e1;font-size:18px}.article-intro-v2{padding:clamp(66px,8vw,112px) clamp(20px,7vw,110px);display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;background:#f7f7f4}.article-intro-v2 h2,.editorial-v2 h2{font-size:clamp(30px,4.4vw,58px);line-height:1.42;margin:10px 0}.article-intro-v2>p{font-size:17px;color:#56616b;margin:0}.article-grid-v2{padding:10px clamp(20px,7vw,110px) clamp(70px,8vw,112px);display:grid;grid-template-columns:repeat(2,1fr);gap:16px;background:#f7f7f4}.article-v2-card{overflow:hidden;border-radius:24px;background:#fff;border:1px solid #e0e4e1;box-shadow:0 18px 50px rgba(7,23,43,.055);transition:.22s}.article-v2-card:hover{transform:translateY(-4px);box-shadow:0 26px 70px rgba(7,23,43,.1)}.article-image{position:relative;height:280px;overflow:hidden;background:#07172b}.article-image img{width:100%;height:100%;object-fit:cover}.article-image>span{position:absolute;inset:0;background:linear-gradient(0deg,rgba(4,13,24,.42),transparent 56%)}.wound-graphic{display:grid;place-items:center;background:radial-gradient(circle at 30% 30%,#2d5962,#0d2831 58%,#071720)}.wound-graphic i{position:absolute;border-radius:50%;border:1px solid rgba(221,194,135,.22)}.wound-graphic i:nth-child(1){width:210px;height:210px}.wound-graphic i:nth-child(2){width:150px;height:150px;border-style:dashed}.wound-graphic i:nth-child(3){width:88px;height:88px}.wound-graphic b{position:relative;color:#ddc287;letter-spacing:.14em}.article-copy-v2{padding:26px 28px 30px}.article-copy-v2 .tag{display:inline-flex;padding:4px 10px;border-radius:999px;background:#f1eee6;color:#8e692d;font-size:10px;font-weight:900}.article-copy-v2 h2{font-size:clamp(22px,2.6vw,31px);line-height:1.5;margin:13px 0 8px}.article-copy-v2 p{color:#5d6976;font-size:14px}.article-copy-v2 a{display:inline-block;margin-top:18px;color:#80602a;font-size:12px;font-weight:900;text-decoration:none}.editorial-v2{padding:clamp(62px,8vw,112px) clamp(20px,7vw,110px);background:#07172b;color:#fff;display:flex;justify-content:space-between;align-items:end;gap:40px}.editorial-v2 p{max-width:820px;color:#c5ced7}.editorial-v2>a{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:10px 20px;border-radius:999px;background:#b58d48;color:#fff;text-decoration:none;font-weight:900;flex:none}
  @media(max-width:900px){.article-intro-v2,.article-grid-v2{grid-template-columns:1fr}.editorial-v2{align-items:flex-start;flex-direction:column}.article-intro-v2{gap:24px}}
  @media(max-width:620px){.articles-v2-hero h1{font-size:44px}.article-image{height:230px}.article-copy-v2{padding:22px}.editorial-v2>a{width:100%}}
</style>
